### ISSUE TITLE
Move policy

### ISSUE THREAD

**Issue by imatrycode** [eoprede/fortigate_api#5]
Hi, loving this first of all,

I've ended up using it for automating a lot of stuff, setting up vips, creating policies, ipsec Vpns and more as once I got the schema I could suss it out.

The one thing I'm struggling with is moving policies , I'm trying to move a policy before another but can't see anywhere in the schema that says how to do this.

I've trailed the web and found a doc suggesting you can do so using put and you add before or after as additional parameters but I can't suss it 

Just wondering if you ever managed to do so as I can see it's on your readme as a nice to have.

Would be awesome if you could

**Comment by eoprede** [comment]
Take a look here: https://github.com/eoprede/ansible_fortios_api/blob/master/fortios/fortios_api_firewall_policy.py
Lines 284 and below.

**Comment by imatrycode** [comment]
Nice one thank you, I have got this now:

# Move Before
t.print_data (t.edit(['cmdb', 'firewall', 'policy', '3'], params={"action": "move", "before": "1"}))

# Move after
t.print_data (t.edit(['cmdb', 'firewall', 'policy', '3'], params={"action": "move", "after": "1"}))

**Comment by imatrycode** [comment]
I'll have a look, I've never really done too much with ansible, at the minute I have a python flask app running in a wscgi environment , each endpoint is providing a different acction e.g. 

/Newnat

/Deletenat

Etc.

And I just post args to the flask app from my php site (ussually a form and I can validate it all phone side) , the app will parse the args and use them on the script.

It's working really well at the minute, could this all be done with ansible or would I have to triggure the events through a gui

**Comment by eoprede** [comment]
Ansible is suited better as configuration management tool - for example you want to run it once an hour to ensure config you have is correct and overwrite config if it is wrong, or in its simple form - you simply want to ensure that these 10 policies are present on the device and you don't want to worry whether some of them exist and need to be modified or if they need to be created, etc. 
For one-off changes that you are doing, especially if you want it to feel like API - Ansible would be just too annoying to deal with without adding any benefits.

**Comment by eoprede** [comment]
Answer provided, documentation updated.
